# Generated by Django 6.0.5 on 2026-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableTool',
        ),
        migrations.AddField(
            model_name='usertool',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon for UI display', max_length=10, null=True),
        ),
    ]
