# Generated by Django 6.0.5 on 2026-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_delete_availabletool_usertool_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model_name',
            field=models.CharField(default='gpt-4o-mini', help_text='AI model used for this session', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='default_model',
            field=models.CharField(choices=[('gpt-5-mini', 'GPT-5 Mini (Recommended)'), ('gpt-5-nano', 'GPT-5 Nano (Smaller/Faster)'), ('gpt-4.1-mini', 'GPT-4.1 Mini (Faster/Cheaper)'), ('gpt-4o-mini', 'GPT-4o Mini (Faster/Cheaper)'), ('o4-mini', 'GPT-o4 Mini (Reasoning)')], default='gpt-4o-mini', help_text='Default AI model for new conversations', max_length=100),
        ),
    ]
